import 'dart:convert';
import 'package:http/http.dart' as http;
import '../models/soil/soilmodel.dart';

class SoilApiHelper {
  static const String _baseUrl = 'https://soil.narc.gov.np/soil/soildata/';

  static Future<Autogenerated?> fetchSoilData({
    required double lat,
    required double lon,
  }) async {
    // Log the lat and lon to check if they are correct
    print("Latitude: $lat, Longitude: $lon");

    // Encode the URL parameters to avoid any issues with special characters
    final url = Uri.parse(
      '$_baseUrl?lat=${Uri.encodeComponent(lat.toString())}&lon=${Uri.encodeComponent(lon.toString())}',
    );

    try {
      final response = await http.get(url);

      if (response.statusCode == 200) {
        final Map<String, dynamic> data = json.decode(response.body);
        return Autogenerated.fromJson(data);
      } else {
        throw Exception('Failed to load data (status: ${response.statusCode})');
      }
    } catch (e) {
      throw Exception('Error fetching soil data: $e');
    }
  }
}
