class Autogenerated {
  Coord? coord;
  String? ph;
  String? organicMatter;
  String? totalNitrogen;
  String? potassium;
  String? p2o5;
  String? boron;
  String? zinc;
  String? sand;
  String? clay;
  String? slit;
  String? parentsoil;
  String? province;
  String? district;
  String? palika;
  Fertilizer? fertilizer;

  Autogenerated({
    this.coord,
    this.ph,
    this.organicMatter,
    this.totalNitrogen,
    this.potassium,
    this.p2o5,
    this.boron,
    this.zinc,
    this.sand,
    this.clay,
    this.slit,
    this.parentsoil,
    this.province,
    this.district,
    this.palika,
    this.fertilizer,
  });

  Autogenerated.fromJson(Map<String, dynamic> json) {
    coord = json['coord'] != null ? new Coord.fromJson(json['coord']) : null;
    ph = json['ph'];
    organicMatter = json['organic_matter'];
    totalNitrogen = json['total_nitrogen'];
    potassium = json['potassium'];
    p2o5 = json['p2o5'];
    boron = json['boron'];
    zinc = json['zinc'];
    sand = json['sand'];
    clay = json['clay'];
    slit = json['slit'];
    parentsoil = json['parentsoil'];
    province = json['province'];
    district = json['district'];
    palika = json['palika'];
    fertilizer =
        json['fertilizer'] != null
            ? new Fertilizer.fromJson(json['fertilizer'])
            : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.coord != null) {
      data['coord'] = this.coord!.toJson();
    }
    data['ph'] = this.ph;
    data['organic_matter'] = this.organicMatter;
    data['total_nitrogen'] = this.totalNitrogen;
    data['potassium'] = this.potassium;
    data['p2o5'] = this.p2o5;
    data['boron'] = this.boron;
    data['zinc'] = this.zinc;
    data['sand'] = this.sand;
    data['clay'] = this.clay;
    data['slit'] = this.slit;
    data['parentsoil'] = this.parentsoil;
    data['province'] = this.province;
    data['district'] = this.district;
    data['palika'] = this.palika;
    if (this.fertilizer != null) {
      data['fertilizer'] = this.fertilizer!.toJson();
    }
    return data;
  }
}

class Coord {
  double? lon;
  double? lat;
  double? elevation;

  Coord({this.lon, this.lat, this.elevation});

  Coord.fromJson(Map<String, dynamic> json) {
    lon = json['lon'];
    lat = json['lat'];
    elevation = json['elevation'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['lon'] = this.lon;
    data['lat'] = this.lat;
    data['elevation'] = this.elevation;
    return data;
  }
}

class Fertilizer {
  Maize? maize;
  Maize? rice;
  Wheat? wheat;

  Fertilizer({this.maize, this.rice, this.wheat});

  Fertilizer.fromJson(Map<String, dynamic> json) {
    maize = json['Maize'] != null ? new Maize.fromJson(json['Maize']) : null;
    rice = json['Rice'] != null ? new Maize.fromJson(json['Rice']) : null;
    wheat = json['Wheat'] != null ? new Wheat.fromJson(json['Wheat']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.maize != null) {
      data['Maize'] = this.maize!.toJson();
    }
    if (this.rice != null) {
      data['Rice'] = this.rice!.toJson();
    }
    if (this.wheat != null) {
      data['Wheat'] = this.wheat!.toJson();
    }
    return data;
  }
}

class Maize {
  OPV? oPV;
  OPV? hybrid;

  Maize({this.oPV, this.hybrid});

  Maize.fromJson(Map<String, dynamic> json) {
    oPV = json['OPV'] != null ? new OPV.fromJson(json['OPV']) : null;
    hybrid = json['Hybrid'] != null ? new OPV.fromJson(json['Hybrid']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.oPV != null) {
      data['OPV'] = this.oPV!.toJson();
    }
    if (this.hybrid != null) {
      data['Hybrid'] = this.hybrid!.toJson();
    }
    return data;
  }
}

class OPV {
  String? mOP;
  String? dAP;
  String? uREA1;
  String? uREA2;
  String? uREA3;
  String? organic;
  String? zinc;
  String? boron;

  OPV({
    this.mOP,
    this.dAP,
    this.uREA1,
    this.uREA2,
    this.uREA3,
    this.organic,
    this.zinc,
    this.boron,
  });

  OPV.fromJson(Map<String, dynamic> json) {
    mOP = json['MOP'];
    dAP = json['DAP'];
    uREA1 = json['UREA1'];
    uREA2 = json['UREA2'];
    uREA3 = json['UREA3'];
    organic = json['organic'];
    zinc = json['zinc'];
    boron = json['boron'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['MOP'] = this.mOP;
    data['DAP'] = this.dAP;
    data['UREA1'] = this.uREA1;
    data['UREA2'] = this.uREA2;
    data['UREA3'] = this.uREA3;
    data['organic'] = this.organic;
    data['zinc'] = this.zinc;
    data['boron'] = this.boron;
    return data;
  }
}

class Wheat {
  OPV? oPV;

  Wheat({this.oPV});

  Wheat.fromJson(Map<String, dynamic> json) {
    oPV = json['OPV'] != null ? new OPV.fromJson(json['OPV']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.oPV != null) {
      data['OPV'] = this.oPV!.toJson();
    }
    return data;
  }
}
